# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '点吧' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 点吧

  target '点吧Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '点吧UITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod "AFNetworking"
end
